backends:
  # simulation backends - numpy is available by default
  - name: qibojit
    class: JITCustomBackend
    from: qibo.backends.jit

  - name: qibotf
    class: TensorflowCustomBackend
    from: qibo.backends.tensorflow

  - name: tensorflow
    class: TensorflowBackend
    from: qibo.backends.tensorflow

  # hardware backends
  - name: qiboicarusq
    class: IcarusQBackend
    from: qibo.backends.hardware
    is_hardware: True

# default active backend after importing all modules
default: qibojit
